.TH "PAM_AUTOLOGIN" "8" "05/02/2022" "PAM Modules Manual" "PAM Modules Manual"
.nh
.ad l
.SH "NAME"
pam_autologin \- automatically login using a remembered password
.SH "DESCRIPTION"
.PP
pam_autologin is a PAM module that automatically logs in using a saved
username and password.
.PP
To enable this module, add it first on the auth list in the PAM
configuration file. Create an empty /etc/security/autologin.conf
file. pam_autologin will detect this file, and that it is empty, and
will save the first non-root username and password in it. During the
next login, the module will automatically authenticate using the saved
credentials.
.PP
Only the first login on each tty is automated unless the "always" option
is given to the module in PAM configuration. /var/log/wtmp is used to
determine if the login is first. When the user logs out, it is likely
with the intent to log in to a different account, so autologin should
not occur.
.PP
To disable autologin, delete the /etc/security/autologin.conf file.
It is prudent to overwrite the file with zeroes before deletion, by
using the shred program from coreutils for example, to avoid leaking
the password into the unused storage area, where it may or may not be
accessible when reading the raw drive data. The contents of the file are
obfuscated with a random key, but obviously can not be made unrecoverable
since autologin must parse it without user assistance.
.SH "OPTIONS"
.PP
Option "always" can be given to autologin every time, instead of only
for the first login on the target tty.
.SH "EXAMPLES"
.PP
auth required pam_autologin.so
.SH "SEE ALSO"
.PP
\fBpam.conf\fR(5),
\fBpam\fR(8)
